name: abjad-ext-nauert

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14-dev"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Log environment variable(s)
      run: |
        python --version
        python -m pip install --upgrade pip coverage
        echo HOME:
        echo $HOME
        echo GITHUB_WORKSPACE:
        echo $GITHUB_WORKSPACE
        echo PATH:
        echo $PATH
        echo PYTHONPATH:
        echo $PYTHONPATH
    - name: Install LilyPond
      run: |
        lilypond_version=2.25.22
        lilypond_archive=lilypond-${lilypond_version}-linux-x86_64.tar.gz
        lilypond_url=https://gitlab.com/lilypond/lilypond/-/releases/
        lilypond_url=${lilypond_url}/v${lilypond_version}/downloads/${lilypond_archive}
        echo ${lilypond_url}
        cd /tmp
        wget -q ${lilypond_url}
        tar -xf ${lilypond_archive}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Abjad
      run: |
        git clone https://github.com/Abjad/abjad.git /tmp/abjad
        pip install /tmp/abjad[dev]
    - name: Install Nauert
      run: |
        python -m pip install -e .
        black --version
        flake8 --version
        isort --version
        mypy --version
        pip --version
        pytest --version
    - name: Run checks and tests
      run: |
        export MYPYPATH=$MYPYPATH:/tmp/abjad
        echo $MYPYPATH
        make black-check
        make flake8
        make isort-check
        make mypy
        make pytest
